# backend, mariadb

version: "3"

services:
  # springboot
  # - 배열 형식
  app:
    container_name: chicken_knowget_backend
    depends_on:
      - database
    ports:
      - "8972:8888"
    build: .

    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/knowget?useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    links:
      - database
    #    platform: linux/arm64 맥 호환성 추가

    # 서버 실행하다 문제 생기면 다시 시작
    restart: always

  # mariadb
  database:
    image: mariadb:10.6.16
    container_name: chicken_knowgetdb
    environment:
      MARIADB_ROOT_PASSWORD: root
#      MARIADB_USER: root
#      MARIADB_PASSWORD: root
      MARIADB_DATABASE: knowget

    # port를 변경하고 application.yaml에서도 포트 번호를 맞춤
    ports:
      - "6033:3306"

#    volumes:
#      - ./src/main/resources/database/initdb.d/:/docker-entrypoint-initdb.d/
#      - ./src/main/resources/database/initdb.d/:/docker-entrypoint-initdb.d/


